### PR TITLE
Do not forget to add extra options when sinking to BQ

### PR DESCRIPTION
**Pull request by hayssams**

### CODE REVIEW

**Review by mhdkassir — APPROVED** [review]
LGTM

**Review by mhdkassir — APPROVED** [review]
LGTM

**Review by mhdkassir — CHANGES_REQUESTED** [review]
Build failing because BigQuerySparkJob.scala needs code format

**Review by hayssams — COMMENTED** [review]
LGTM

**Review by mhdkassir — APPROVED** [review]

**Pull request merged**
